# Generated by Django 6.0.6 on 2026-06-07 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carStore', '0002_car_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='kilometers',
            field=models.IntegerField(default=0, verbose_name='Quilometragem'),
        ),
    ]
