# Generated by Django 6.0.6 on 2026-06-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carStore', '0005_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Placa'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
